import { I8n } from "./types.js";

export default {
  userNotInVoiceChannel: 'Lệnh chỉ có thể sử dụng trong kênh voice!',
  userNotInChanel: 'Lệnh chỉ có thể sử dụng trong kênh!',
  userNotInGuild: 'Bạn không ở trong một server hoặc guild nào để sử dụng lệnh',
  autoPlayResponse: 'Tự động phát nhạc: {status}',
  incorrectLoopMode: "Câu hình lặp không hợp lệp. Các cấu hình hợp lệ gồm `single`, `all` hoặc `off`",
  notEnoughArguments: 'Không đủ tham số đề với lệnh {args}',
  loopModeNone: 'Câu hình lặp hóa: `Không lặp`',
  loopModeSingle: 'Câu hình lặp hóa: `Lặp 1 bài hát`',
  loopModeAll: 'Câu hình lặp hóa: `Lặp tất cả bài hát`',
  noSongsInQueue: 'Không có bài hát trong queue',
  currentPlaying: 'Bài đang phát: {title} bởi {author}',
  pauseSongs: 'Dừng tất cả bài hát trong queue',
  missingQuery: 'Bạn cần phải cung cấp 1 truy vấn để sử dụng lệnh này',
  noResults: 'Không tìm thấy tập phát nây',
  addedPlaylistToQueue: 'Thêm **{num_of_songs}** bài hát của playlist **{playlist_name}** vào queue',
  addedSongToQueue: 'Thêm bài hát **{song_title}** bởi **{song_author}** vào queue',
  emptyQueue: 'Không có bài hát nào trong hàng chờ',
  resumeSongs: "Bài hát đã được tiếp tục",
  skippedSong: 'Bài hát được bỏ qua',
  stoppedPlaying: 'Dừng tất cả bài hát trong queue',
  settedVolume: 'Đặt lượng nhạc: {volume}',
  playingSongEmbed: 'Bài phát bài hát: **{title}** bởi **{author}**',
  playingSong: 'Bài phát bài hát: **{title}** bởi **{author}**',
  playerEnded: 'Đã phát xong',
  playerDestroyed: 'Đã dừng vì không hoạt động trong một khoảng thời gian.',
  cooldown: "Bạn phải chờ {time} giây trước khi sử dụng lệnh này.",
  missingPermissions: `Bạn không có quyền để sử dụng lệnh này.\n\n-# Thiếu quyền: {permissions}`,
  botMissingPermissions: "Bot không có quyền để thực hiện lệnh này.\n\n-# Thiếu quyền: {permissions}",
  commandNotAllowed: 'Bạn không thể sử dụng lệnh ở nơi đây\n\n-# Mã lỗi: ${code}',
  commandError: 'Đã xảy ra lỗi khi thực hiện lệnh này.\n\n-# Mã lỗi: {error}',
} satisfies I8n